version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/developers-registration
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/developers-registration
    volumes:
      - ./dist/:/usr/src/developers-registration/dist/
      - ./package.json:/usr/src/developers-registration/package.json
    ports:
      - "3000:3000"
    links:
      - mongo